indexdomconnect = {name: "indexdomconnect"}

############################################################
indexdomconnect.initialize = () ->
    global.deploycontractpageContent = document.getElementById("deploycontractpage-content")
    global.newOwner0Address = document.getElementById("new-owner0-address")
    global.newOwner1Address = document.getElementById("new-owner1-address")
    global.newOwner2Address = document.getElementById("new-owner2-address")
    global.changecontractpageContent = document.getElementById("changecontractpage-content")
    global.knownContractsContainer = document.getElementById("known-contracts-container")
    global.newAddressInput = document.getElementById("new-address-input")
    global.settingspageContent = document.getElementById("settingspage-content")
    global.idDisplay = document.getElementById("id-display")
    global.secretManagerInput = document.getElementById("secret-manager-input")
    global.dataManagerInput = document.getElementById("data-manager-input")
    global.content = document.getElementById("content")
    global.owner0Address = document.getElementById("owner0-address")
    global.owner1Address = document.getElementById("owner1-address")
    global.owner2Address = document.getElementById("owner2-address")
    global.owner3Address = document.getElementById("owner3-address")
    global.owner4Address = document.getElementById("owner4-address")
    global.owner5Address = document.getElementById("owner5-address")
    global.owner6Address = document.getElementById("owner6-address")
    global.owner7Address = document.getElementById("owner7-address")
    global.owner8Address = document.getElementById("owner8-address")
    global.owner9Address = document.getElementById("owner9-address")
    global.owner10Address = document.getElementById("owner10-address")
    global.owner11Address = document.getElementById("owner11-address")
    global.contractType = document.getElementById("contract-type")
    global.addressDisplay = document.getElementById("address-display")
    global.statusMessageDisplay = document.getElementById("status-message-display")
    global.changeContractButton = document.getElementById("change-contract-button")
    global.deployNewButton = document.getElementById("deploy-new-button")
    global.clickCatcher = document.getElementById("click-catcher")
    global.popup = document.getElementById("popup")
    global.popupTitle = document.getElementById("popup-title")
    global.popupCloseButton = document.getElementById("popup-close-button")
    global.popupContent = document.getElementById("popup-content")
    global.connectWalletButton = document.getElementById("connect-wallet-button")
    global.headerRight = document.getElementById("header-right")
    return
    
module.exports = indexdomconnect